services:
  gateway:
    build:
      context: ./backend/gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "3000:3000"
    environment:
      - API_SERVER_URL=http://api:3001
      - WS_SERVER_URL=http://ws:3002
      - GATEWAY_PORT=3000
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - api
      - ws
    networks:
      - app-network
    restart: unless-stopped

  api:
    build:
      context: ./backend/API-server
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL_WEB=${MONGO_URL_WEB}
      - MONGO_URL_LOCAL=${MONGO_URL_LOCAL}
      - DB_LOCAL=${DB_LOCAL}
      - FIREBASE_URL=${FIREBASE_URL}
      - API_PORT=3001
      - CORS_ORIGIN_API=${CORS_ORIGIN_API}
    networks:
      - app-network
    restart: unless-stopped

  ws:
    build:
      context: ./backend/WS-server
      dockerfile: Dockerfile
    container_name: ws-server
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL_WEB=${MONGO_URL_WEB}
      - MONGO_URL_LOCAL=${MONGO_URL_LOCAL}
      - DB_LOCAL=${DB_LOCAL}
      - PORT=3002
      - CORS_ORIGIN_WS=${CORS_ORIGIN_WS}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/vueFrontEndService
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API=${VITE_API:-http://gateway:3000/api}
      - VITE_WS=${VITE_WS:-http://gateway:3000}
    depends_on:
    - gateway
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
