services:
  frontend:
    build:
      context: ./frontend/vueFrontEndService
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API=${VITE_API:-http://gateway:3000/api}
      - VITE_WS=${VITE_WS:-http://gateway:3000}
    restart: unless-stopped