services:
  gateway:
    build:
      context: ./backend/gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - API_SERVER_URL=http://api:${API_PORT}
      - WS_SERVER_URL=http://ws:${WS_PORT}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - api
      - ws
    networks:
      - app-network
    restart: unless-stopped

  api:
    build:
      context: ./backend/API-server
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - MONGO_URL_WEB=${MONGO_URL_WEB}
      - MONGO_URL_LOCAL=${MONGO_URL_LOCAL}
      - DB_LOCAL=${DB_LOCAL}
      - FIREBASE_URL=${FIREBASE_URL}
      - API_PORT=${API_PORT}
      - CORS_ORIGIN_API=${CORS_ORIGIN_API}
    networks:
      - app-network
    restart: unless-stopped

  ws:
    build:
      context: ./backend/WS-server
      dockerfile: Dockerfile
    container_name: ws-server
    ports:
      - "${WS_PORT}:${WS_PORT}"
    environment:
      - MONGO_URL_WEB=${MONGO_URL_WEB}
      - MONGO_URL_LOCAL=${MONGO_URL_LOCAL}
      - DB_LOCAL=${DB_LOCAL}
      - PORT=${WS_PORT}
      - CORS_ORIGIN_WS=${CORS_ORIGIN_WS}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/vueFrontEndService
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API=${VITE_API:-http://gateway:{GATEWAY_PORT}/api}
      - VITE_WS=${VITE_WS:-http://gateway:{GATEWAY_PORT}}
    depends_on:
    - gateway
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
