{{- $releaseName := .Release.Name -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-ws-config
  namespace: {{ .Values.app.namespace }}
  labels:
    name: {{ $releaseName }}-ws
data:
  ws-url: 'http://{{ $releaseName }}-ws-service:{{ .Values.backend.ws.port}}'
