apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dnd
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
  mongo-url-local: bW9uZ29kYjovL21vbmdvdXNlcjptb25nb3Bhc3N3b3JkQG1vbmdvLTAubW9uZ28tc2VydmljZToyNzAxNy9EbkRUZXN0P2F1dGhTb3VyY2U9YWRtaW4=
  db-local: dHJ1ZQ==
  firebase_url: ZG5kc2VydmljZS04ODFjYS5maXJlYmFzZXN0b3JhZ2UuYXBw