{{- $releaseName := .Release.Name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-api-deployment
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ $releaseName }}-api
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ $releaseName }}-api
  template:
    metadata:
      labels:
        app: {{ $releaseName }}-api
    spec:
      volumes:
      - name: firebase-admin
        secret:
          secretName: firebase-admin
      containers:
      - name: {{ $releaseName }}-api-pod
        image: "{{ .Values.backend.api.repo }}:{{ .Values.backend.api.tag }}"
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.backend.resources.requests.memory | quote }}
            cpu: {{ .Values.backend.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory | quote }}
            cpu: {{ .Values.backend.resources.limits.cpu | quote }}
        ports:
        - containerPort: {{ .Values.backend.api.port }}
        volumeMounts:
        - name: firebase-admin
          mountPath: /app/firebase-admin.json
          subPath: firebase-admin.json
        env:
        - name: DB_LOCAL
          valueFrom:
            configMapKeyRef:
              name: {{ $releaseName }}-mongo-config
              key: local
        - name: MONGO_URL_LOCAL
          valueFrom:
            configMapKeyRef:
              name: {{ $releaseName }}-mongo-config
              key: mongo-url
        - name: CORS_ORIGIN_API
          valueFrom:
            configMapKeyRef:
              name: {{ $releaseName }}-gateway-config
              key: gateway-url
        - name: FIREBASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ $releaseName }}-mongo-config
              key: firebase-url
        - name: API_PORT
          value: {{ .Values.backend.api.port | quote }}
