{{- $releaseName := .Release.Name -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-api-service
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ $releaseName }}-api
spec:
  selector:
    app: {{ $releaseName }}-api
  ports:
  - port: {{ .Values.backend.api.port }}
    targetPort: {{ .Values.backend.api.port }}
