apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dnd
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: firebase-admin
          secret:
            secretName: firebase-admin
      containers:
      - name: api-pod
        image: api:1.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: firebase-admin
          mountPath: /app/firebase-admin.json
          subPath: firebase-admin.json
        env:
        - name: DB_LOCAL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: db-local
        - name: MONGO_URL_LOCAL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mongo-url-local
        - name: CORS_ORIGIN_API
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: gateway-url
        - name: FIREBASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: firebase_url
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: api-port
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dnd
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: 3001
    targetPort: 3001

