apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
  namespace: dnd
  labels:
    name: vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
      - name: vue
        image: vue:1.1.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "256m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: VITE_API
          valueFrom:
            configMapKeyRef:
              name: vue-config
              key: api-url
        - name: VITE_WS
          valueFrom:
            configMapKeyRef:
              name: vue-config
              key: ws-url
---
apiVersion: v1
kind: Service
metadata:
  name: vue-service
  namespace: dnd
  labels:
    name: vue
spec:
  selector:
    app: vue
  ports:
  - port: 80
    targetPort: 80

